#!/bin/bash -ex

echo "Setup running"

# Install Python packages
sudo pip install opencv-python
sudo pip install numpy
sudo pip install tesserocr
sudo pip install pillow
sudo pip install matplotlib
sudo pip install scipy
sudo pip install fuzzyset

exit 1